name: weather_app
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  chopper: ^7.0.7+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.3
  intl: ^0.18.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  chopper_generator: ^7.0.5+1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.4
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  riverpod_generator: ^2.3.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
